package com.mediatek.wwtv.tvcenter.epg;

public class EPGConfig {
    public static final int AVOID_PROGRAM_FOCUS_CHANGE = 26;
    public static final int EPG_CHANGING_CHANNEL = 280;
    public static final int EPG_CHANGING_CH_TIMEOUT = 281;
    public static final int EPG_DATA_RETRIEVAL_FININSH = 5;
    public static final int EPG_DATA_RETRIEVING = 4;
    public static final int EPG_EVENT_REASON_SCHEDULE_UPDATE_REPEAT = 6;
    public static final int EPG_GET_EVENT_LIST_DELAY_LONG = 277;
    public static final int EPG_GET_TIF_EVENT_LIST = 263;
    public static final int EPG_INIT_EVENT_LIST = 275;
    public static final int EPG_LIST_ITME_COUNT = 6;
    public static final int EPG_MUTE_VIDEO_AND_AUDIO = 288;
    public static final int EPG_NOTIFY_LIST_ADAPTER = 265;
    public static final int EPG_PROGRAMINFO_SHOW = 260;
    public static final int EPG_PROGRAM_STTL_SHOW = 261;
    public static final int EPG_REFRESH_CHANNEL_LIST = 278;
    public static final int EPG_SELECT_CHANNEL_COMPLETE = 273;
    public static final int EPG_SETMUTE_SOUND = 279;
    public static final int EPG_SET_LIST_ADAPTER = 264;
    public static final int EPG_SET_LOCK_ICON = 276;
    public static final int EPG_SHOW_LOCK_ICON = 272;
    public static final int EPG_SYNCHRONIZATION_MESSAGE = 259;
    public static final int EPG_UPDATE_API_EVENT_LIST = 274;
    public static final int EPG_UPDATE_CHANNEL_LIST = 262;
    public static final int FROM_ANOTHER_STREAM = 25;
    public static final int FROM_KEYCODE_DPAD_LEFT = 21;
    public static final int FROM_KEYCODE_DPAD_RIGHT = 22;
    public static final int FROM_KEYCODE_MTKIR_GREEN = 24;
    public static final int FROM_KEYCODE_MTKIR_OTHER = -1;
    public static final int FROM_KEYCODE_MTKIR_RED = 23;
    public static int FROM_WHERE = 27;
    public static int SELECTED_CHANNEL_POSITION = 0;
    public static final int SET_LAST_POSITION = 27;
    public static boolean avoidFoucsChange = false;
    public static boolean init = true;
    public static final int mMaxDayNum = 8;
    public static final int mTimeSpan = 2;
}
