package com.mediatek.twoworlds.tv.common;

public class MtkTvSvctxNotifyCode {
    public static final int SVCTX_NTFY_CODE_ANA_AUTO_DETECTED_AUD_SYS;
    public static final int SVCTX_NTFY_CODE_AUDIO_AUTO_MUTE;
    public static final int SVCTX_NTFY_CODE_AUDIO_AUTO_UNMUTE;
    public static final int SVCTX_NTFY_CODE_AUDIO_DMUTE_AMUTE;
    public static final int SVCTX_NTFY_CODE_AUDIO_DMUTE_AUNMUTE;
    public static final int SVCTX_NTFY_CODE_AUDIO_DUNMUTE_AMUTE;
    public static final int SVCTX_NTFY_CODE_AUDIO_DUNMUTE_AUNMUTE;
    public static final int SVCTX_NTFY_CODE_AUDIO_FMT_UPDATE;
    public static final int SVCTX_NTFY_CODE_AUDIO_ONLY_STRM;
    public static final int SVCTX_NTFY_CODE_AUDIO_ONLY_SVC;
    public static final int SVCTX_NTFY_CODE_AUDIO_STREAM_CTR_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_AUDIO_VIDEO_SVC;
    public static final int SVCTX_NTFY_CODE_AUD_SYS_DETECTED;
    public static final int SVCTX_NTFY_CODE_BRDCSTING_SVC;
    public static final int SVCTX_NTFY_CODE_BUF_READY;
    public static final int SVCTX_NTFY_CODE_CA;
    public static final int SVCTX_NTFY_CODE_CAM_CARD_REMOVE;
    public static final int SVCTX_NTFY_CODE_CC_ATTR_CHANGED;
    public static final int SVCTX_NTFY_CODE_CC_IDX_CHANGED;
    public static final int SVCTX_NTFY_CODE_CHAPTER_CHANGE;
    public static final int SVCTX_NTFY_CODE_CH_SRC_FROM_SCART;
    public static final int SVCTX_NTFY_CODE_CH_SRC_FROM_TUNER;
    public static final int SVCTX_NTFY_CODE_CMPB_QUERY;
    public static final int SVCTX_NTFY_CODE_CONNECTION_ANA_FREQ;
    public static final int SVCTX_NTFY_CODE_CONN_PMT_UPDATED;
    public static final int SVCTX_NTFY_CODE_CP;
    public static final int SVCTX_NTFY_CODE_CRNT_EVN_NOT_READY;
    public static final int SVCTX_NTFY_CODE_CRNT_EVN_READY;
    public static final int SVCTX_NTFY_CODE_CRNT_EVN_START_QUERY;
    public static final int SVCTX_NTFY_CODE_DELIVERY_SYSTEM_CHANGE;
    public static final int SVCTX_NTFY_CODE_DRM_CAD_ACQUISITION_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_CAD_INVALID;
    public static final int SVCTX_NTFY_CODE_DRM_CERT_EXPIRED;
    public static final int SVCTX_NTFY_CODE_DRM_CONTENT_EXHAUSTED;
    public static final int SVCTX_NTFY_CODE_DRM_DEV_NOT_REG;
    public static final int SVCTX_NTFY_CODE_DRM_GET_KEY_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_INIT_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_INVALID_ARG;
    public static final int SVCTX_NTFY_CODE_DRM_INV_ASSET_ID;
    public static final int SVCTX_NTFY_CODE_DRM_INV_BUSINESS_TKN;
    public static final int SVCTX_NTFY_CODE_DRM_INV_CONTENT_TYPE;
    public static final int SVCTX_NTFY_CODE_DRM_INV_SRV_TKN;
    public static final int SVCTX_NTFY_CODE_DRM_INV_USR_AGENT;
    public static final int SVCTX_NTFY_CODE_DRM_LICENSE_ACQUISITION_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_LICENSE_EXPIRED_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_LICENSE_INVALID;
    public static final int SVCTX_NTFY_CODE_DRM_LICENSE_SERVER_CONNECTION_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_LIC_EXPIRATION_ERR;
    public static final int SVCTX_NTFY_CODE_DRM_LIC_NOT_ALLOW;
    public static final int SVCTX_NTFY_CODE_DRM_MARLIN_KEY_FORMATERROR;
    public static final int SVCTX_NTFY_CODE_DRM_NONE = SVCTX_NTFY_CODE_DRM_STATUS_START;
    public static final int SVCTX_NTFY_CODE_DRM_NOT_MARLIN_MS3_URL;
    public static final int SVCTX_NTFY_CODE_DRM_NO_MARLIN_KEY;
    public static final int SVCTX_NTFY_CODE_DRM_SRVDATA_ACCESS_FAIL;
    public static final int SVCTX_NTFY_CODE_DRM_SRV_BUSY;
    public static final int SVCTX_NTFY_CODE_DRM_SRV_END;
    public static final int SVCTX_NTFY_CODE_DRM_SRV_UNAVAIL;
    public static final int SVCTX_NTFY_CODE_DRM_STATUS_START;
    public static final int SVCTX_NTFY_CODE_DRM_TOKEN_ACQUISITION_ERROR;
    public static final int SVCTX_NTFY_CODE_DRM_TYPE_MARLIN;
    public static final int SVCTX_NTFY_CODE_DRM_TYPE_NAUTILUS_MARLIN;
    public static final int SVCTX_NTFY_CODE_DRM_TYPE_PLAYREADY;
    public static final int SVCTX_NTFY_CODE_DRM_UNKNOWN_ERR;
    public static final int SVCTX_NTFY_CODE_DRM_UNKNOWN_SRV_ERR;
    public static final int SVCTX_NTFY_CODE_DRM_UNKNOW_DRMTYPE;
    public static final int SVCTX_NTFY_CODE_DRM_UNSUPPORTED_VER;
    public static final int SVCTX_NTFY_CODE_DVBS_SHORT_OFF;
    public static final int SVCTX_NTFY_CODE_DVBS_SHORT_ON;
    public static final int SVCTX_NTFY_CODE_END_ALTER_FREQ_TUNE;
    public static final int SVCTX_NTFY_CODE_END_FIRST_TUNE;
    public static final int SVCTX_NTFY_CODE_END_FREQ_LIST_UPDATED_CHK;
    public static final int SVCTX_NTFY_CODE_EWS_OFF;
    public static final int SVCTX_NTFY_CODE_EWS_ON;
    public static final int SVCTX_NTFY_CODE_EXISTED_CC_IND_CHG;
    public static final int SVCTX_NTFY_CODE_HDCP_DETECT;
    public static final int SVCTX_NTFY_CODE_HDCP_NOT_DETECT;
    public static final int SVCTX_NTFY_CODE_INP_SIGNAL_UNKNOWN;
    public static final int SVCTX_NTFY_CODE_INTERNAL_ERROR;
    public static final int SVCTX_NTFY_CODE_INTERRUPTED;
    public static final int SVCTX_NTFY_CODE_IN_STOPPING;
    public static final int SVCTX_NTFY_CODE_MACROVISION_DETECT;
    public static final int SVCTX_NTFY_CODE_MACROVISION_NOT_DETECT;
    public static final int SVCTX_NTFY_CODE_MEDIA_AB_REPEAT_DONE;
    public static final int SVCTX_NTFY_CODE_MEDIA_AS_BIT_RATE_CHG;
    public static final int SVCTX_NTFY_CODE_MEDIA_AS_CODEC_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_MEDIA_AUDIO_SWITCH_DONE;
    public static final int SVCTX_NTFY_CODE_MEDIA_BAD_TICK_N_TO_Y;
    public static final int SVCTX_NTFY_CODE_MEDIA_BAD_TICK_Y_TO_N;
    public static final int SVCTX_NTFY_CODE_MEDIA_CAM_CARD_MISSING;
    public static final int SVCTX_NTFY_CODE_MEDIA_CHAPTER_UPDATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_CLEAR_EOF;
    public static final int SVCTX_NTFY_CODE_MEDIA_DESC_ALLOCED;
    public static final int SVCTX_NTFY_CODE_MEDIA_DRM_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_MEDIA_DURATION_UPDATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_EOF;
    public static final int SVCTX_NTFY_CODE_MEDIA_EOS;
    public static final int SVCTX_NTFY_CODE_MEDIA_ERROR;
    public static final int SVCTX_NTFY_CODE_MEDIA_FILE_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_MEDIA_FILE_OPER_ERROR;
    public static final int SVCTX_NTFY_CODE_MEDIA_FRAMERATE_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_MEDIA_GET_IFRAME;
    public static final int SVCTX_NTFY_CODE_MEDIA_GUIDANCE_BLOCKED_AFT_THUMB;
    public static final int SVCTX_NTFY_CODE_MEDIA_GUIDANCE_BLOCKED_DUR_THUMB;
    public static final int SVCTX_NTFY_CODE_MEDIA_HD_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_MEDIA_LOST;
    public static final int SVCTX_NTFY_CODE_MEDIA_MENU_PRESNT;
    public static final int SVCTX_NTFY_CODE_MEDIA_MSGQ_EMPTY;
    public static final int SVCTX_NTFY_CODE_MEDIA_MSGQ_FULL;
    public static final int SVCTX_NTFY_CODE_MEDIA_NO_CONTENT;
    public static final int SVCTX_NTFY_CODE_MEDIA_PAUSE_STATUS;
    public static final int SVCTX_NTFY_CODE_MEDIA_PB_RANGE_ALLOC;
    public static final int SVCTX_NTFY_CODE_MEDIA_PRE_PROCESSED;
    public static final int SVCTX_NTFY_CODE_MEDIA_PRE_PROCESSING;
    public static final int SVCTX_NTFY_CODE_MEDIA_PVR_PLAYING_PARENT_RATING;
    public static final int SVCTX_NTFY_CODE_MEDIA_PVR_PROG_BLOCKED;
    public static final int SVCTX_NTFY_CODE_MEDIA_PVR_THUMBNAIL_PARENT_RATING;
    public static final int SVCTX_NTFY_CODE_MEDIA_RANGE_AB_DONE;
    public static final int SVCTX_NTFY_CODE_MEDIA_RATING_BLOCKED;
    public static final int SVCTX_NTFY_CODE_MEDIA_RATING_UNBLOCKED;
    public static final int SVCTX_NTFY_CODE_MEDIA_REPEAT_DONE;
    public static final int SVCTX_NTFY_CODE_MEDIA_REPLAY;
    public static final int SVCTX_NTFY_CODE_MEDIA_RESOLUTION_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_MEDIA_SEEK_ERROR;
    public static final int SVCTX_NTFY_CODE_MEDIA_SEEK_READY;
    public static final int SVCTX_NTFY_CODE_MEDIA_SPEED_UPDATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_SUBTITLE_FMT_UPDATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_THUMBNAIL_CANCEL;
    public static final int SVCTX_NTFY_CODE_MEDIA_THUMBNAIL_DONE;
    public static final int SVCTX_NTFY_CODE_MEDIA_TIME_UPDATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_TITLE_UPDATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_UNDERFLOW;
    public static final int SVCTX_NTFY_CODE_MEDIA_UOP_INVALID;
    public static final int SVCTX_NTFY_CODE_MEDIA_URI_FILE_OPENED;
    public static final int SVCTX_NTFY_CODE_MEDIA_VIDEO_PRESENT;
    public static final int SVCTX_NTFY_CODE_MEDIA_VS_BIT_RATE;
    public static final int SVCTX_NTFY_CODE_MEDIA_VS_BIT_RATE_CHG;
    public static final int SVCTX_NTFY_CODE_MEDIA_VS_CODEC_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_NONE = -1;
    public static final int SVCTX_NTFY_CODE_NON_BRDCSTING_SVC;
    public static final int SVCTX_NTFY_CODE_NORMAL = 0;
    public static final int SVCTX_NTFY_CODE_NO_ANY_STREAM;
    public static final int SVCTX_NTFY_CODE_NO_AUDIO_VIDEO_SVC;
    public static final int SVCTX_NTFY_CODE_NO_CC_AVIL_INDICATOR;
    public static final int SVCTX_NTFY_CODE_NO_RESOURCES;
    public static final int SVCTX_NTFY_CODE_NO_STREAM;
    public static final int SVCTX_NTFY_CODE_OUT_OF_SAFE_RANGE_END;
    public static final int SVCTX_NTFY_CODE_OUT_OF_SAFE_RANGE_START;
    public static final int SVCTX_NTFY_CODE_OWN_SERVICE_CHANGING;
    public static final int SVCTX_NTFY_CODE_PIN_CAP_CHANGE;
    public static final int SVCTX_NTFY_CODE_PSI_TABLE_UPDATE;
    public static final int SVCTX_NTFY_CODE_PVR_TRICK_REACH_VALID_RANGE_END;
    public static final int SVCTX_NTFY_CODE_REACH_VALID_RANGE_END;
    public static final int SVCTX_NTFY_CODE_REACH_VALID_RANGE_START;
    public static final int SVCTX_NTFY_CODE_REC_18_PLUS_LOCKED;
    public static final int SVCTX_NTFY_CODE_REC_BAD_TICK;
    public static final int SVCTX_NTFY_CODE_REC_BITRATE_TOO_HIGH;
    public static final int SVCTX_NTFY_CODE_REC_BLOCKED;
    public static final int SVCTX_NTFY_CODE_REC_BUF_FULL;
    public static final int SVCTX_NTFY_CODE_REC_CHANNEL_LOCKED;
    public static final int SVCTX_NTFY_CODE_REC_ES_AUTH_UPDATED;
    public static final int SVCTX_NTFY_CODE_REC_INPUT_LOCKED;
    public static final int SVCTX_NTFY_CODE_REC_INTERNAL_ERROR;
    public static final int SVCTX_NTFY_CODE_REC_NOT_SUPPORTED;
    public static final int SVCTX_NTFY_CODE_REC_PAUSED;
    public static final int SVCTX_NTFY_CODE_REC_PIN_ERROR;
    public static final int SVCTX_NTFY_CODE_REC_REACH_BOUND;
    public static final int SVCTX_NTFY_CODE_REC_REACH_TIME_BOUND;
    public static final int SVCTX_NTFY_CODE_REC_REQ_ES_LIST;
    public static final int SVCTX_NTFY_CODE_REC_REQ_STOP;
    public static final int SVCTX_NTFY_CODE_REC_SOURCE_READY;
    public static final int SVCTX_NTFY_CODE_REC_STARTED;
    public static final int SVCTX_NTFY_CODE_REC_STOPPED;
    public static final int SVCTX_NTFY_CODE_REC_STRG_ERROR;
    public static final int SVCTX_NTFY_CODE_REC_STRG_FULL;
    public static final int SVCTX_NTFY_CODE_REC_UNAUTHORIZED;
    public static final int SVCTX_NTFY_CODE_RF_SCAN_REQUIRED;
    public static final int SVCTX_NTFY_CODE_SCDB_ADD;
    public static final int SVCTX_NTFY_CODE_SCDB_DEL;
    public static final int SVCTX_NTFY_CODE_SCDB_MODIFY;
    public static final int SVCTX_NTFY_CODE_SCRAMBLED_AUDIO_CLEAR_VIDEO_SVC;
    public static final int SVCTX_NTFY_CODE_SCRAMBLED_AUDIO_NO_VIDEO_SVC;
    public static final int SVCTX_NTFY_CODE_SCRAMBLED_AUDIO_VIDEO_SVC;
    public static final int SVCTX_NTFY_CODE_SCRAMBLED_VIDEO_CLEAR_AUDIO_SVC;
    public static final int SVCTX_NTFY_CODE_SCRAMBLED_VIDEO_NO_AUDIO_SVC;
    public static final int SVCTX_NTFY_CODE_SEEK_REACH_VALID_RANGE_END;
    public static final int SVCTX_NTFY_CODE_SERVICE_BLOCKED;
    public static final int SVCTX_NTFY_CODE_SERVICE_CHANGING;
    public static final int SVCTX_NTFY_CODE_SERVICE_LICENSE_TIMEOUT_BLOCKED;
    public static final int SVCTX_NTFY_CODE_SERVICE_LICENSE_TIMEOUT_UNBLOCKED;
    public static final int SVCTX_NTFY_CODE_SERVICE_PIN_BLOCKED;
    public static final int SVCTX_NTFY_CODE_SERVICE_PIN_UNBLOCKED;
    public static final int SVCTX_NTFY_CODE_SERVICE_UNBLOCKED;
    public static final int SVCTX_NTFY_CODE_SIGNAL_DETECTING;
    public static final int SVCTX_NTFY_CODE_SIGNAL_LOCKED;
    public static final int SVCTX_NTFY_CODE_SIGNAL_LOCKED_AS_BLOCKED;
    public static final int SVCTX_NTFY_CODE_SIGNAL_LOSS;
    public static final int SVCTX_NTFY_CODE_SIGNAL_LOSS_AS_BLOCKED;
    public static final int SVCTX_NTFY_CODE_START_ALTER_FREQ_TUNE;
    public static final int SVCTX_NTFY_CODE_START_FIRST_TUNE;
    public static final int SVCTX_NTFY_CODE_START_FREQ_LIST_UPDATED_CHK;
    public static final int SVCTX_NTFY_CODE_STOPPED;
    public static final int SVCTX_NTFY_CODE_STOPPED_BY_PREEMPT;
    public static final int SVCTX_NTFY_CODE_STREAM_OPENED;
    public static final int SVCTX_NTFY_CODE_STREAM_STARTED;
    public static final int SVCTX_NTFY_CODE_STREAM_STARTED_AS_BLOCKED;
    public static final int SVCTX_NTFY_CODE_STREAM_STOPPED;
    public static final int SVCTX_NTFY_CODE_STREAM_STOPPED_AS_BLOCKED;
    public static final int SVCTX_NTFY_CODE_SVCTX_THREAD_KICK_OFF;
    public static final int SVCTX_NTFY_CODE_TRICK_REACH_VALID_RANGE_END;
    public static final int SVCTX_NTFY_CODE_TUNER_SIGNAL_LOCKED;
    public static final int SVCTX_NTFY_CODE_TUNER_SIGNAL_LOSS;
    public static final int SVCTX_NTFY_CODE_TV_SYS_DETECTED;
    public static final int SVCTX_NTFY_CODE_UHD_420_SIGNAL_DETECTED;
    public static final int SVCTX_NTFY_CODE_UHD_420_SIGNAL_NOT_DETECTED;
    public static final int SVCTX_NTFY_CODE_UNFREEZE;
    public static final int SVCTX_NTFY_CODE_VIDEO_ANA_COLOR_SYSTEM;
    public static final int SVCTX_NTFY_CODE_VIDEO_AUTO_CLK_POS_PHS_DONE;
    public static final int SVCTX_NTFY_CODE_VIDEO_AUTO_COLOR_DONE;
    public static final int SVCTX_NTFY_CODE_VIDEO_AUTO_MUTE;
    public static final int SVCTX_NTFY_CODE_VIDEO_AUTO_UNMUTE;
    public static final int SVCTX_NTFY_CODE_VIDEO_FMT_UPDATE;
    public static final int SVCTX_NTFY_CODE_VIDEO_FMT_UPDATE_AS_BLOCKED;
    public static final int SVCTX_NTFY_CODE_VIDEO_NUM_READY;
    public static final int SVCTX_NTFY_CODE_VIDEO_ONLY_STRM;
    public static final int SVCTX_NTFY_CODE_VIDEO_ONLY_SVC;
    public static final int SVCTX_NTFY_CODE_VIDEO_PLAY_DONE;
    public static final int SVCTX_NTFY_CODE_VIDEO_STREAM_CTR_NOT_SUPPORT;
    public static final int SVCTX_NTFY_CODE_VIDEO_WFD_ERROR;
    public static final int SVCTX_NTFY_CODE_WITH_CC_AVIL_INDICATOR;

    static {
        int i = 0 + 1;
        SVCTX_NTFY_CODE_SVCTX_THREAD_KICK_OFF = i;
        int i2 = i + 1;
        SVCTX_NTFY_CODE_DELIVERY_SYSTEM_CHANGE = i2;
        int i3 = i2 + 1;
        SVCTX_NTFY_CODE_SIGNAL_DETECTING = i3;
        int i4 = i3 + 1;
        SVCTX_NTFY_CODE_SIGNAL_LOCKED = i4;
        int i5 = i4 + 1;
        SVCTX_NTFY_CODE_SIGNAL_LOSS = i5;
        int i6 = i5 + 1;
        SVCTX_NTFY_CODE_INTERRUPTED = i6;
        int i7 = i6 + 1;
        SVCTX_NTFY_CODE_SERVICE_CHANGING = i7;
        int i8 = i7 + 1;
        SVCTX_NTFY_CODE_OWN_SERVICE_CHANGING = i8;
        int i9 = i8 + 1;
        SVCTX_NTFY_CODE_SERVICE_BLOCKED = i9;
        int i10 = i9 + 1;
        SVCTX_NTFY_CODE_SIGNAL_LOSS_AS_BLOCKED = i10;
        int i11 = i10 + 1;
        SVCTX_NTFY_CODE_SIGNAL_LOCKED_AS_BLOCKED = i11;
        int i12 = i11 + 1;
        SVCTX_NTFY_CODE_SERVICE_UNBLOCKED = i12;
        int i13 = i12 + 1;
        SVCTX_NTFY_CODE_STOPPED = i13;
        int i14 = i13 + 1;
        SVCTX_NTFY_CODE_STOPPED_BY_PREEMPT = i14;
        int i15 = i14 + 1;
        SVCTX_NTFY_CODE_IN_STOPPING = i15;
        int i16 = i15 + 1;
        SVCTX_NTFY_CODE_CRNT_EVN_START_QUERY = i16;
        int i17 = i16 + 1;
        SVCTX_NTFY_CODE_CRNT_EVN_NOT_READY = i17;
        int i18 = i17 + 1;
        SVCTX_NTFY_CODE_CRNT_EVN_READY = i18;
        int i19 = i18 + 1;
        SVCTX_NTFY_CODE_NO_AUDIO_VIDEO_SVC = i19;
        int i20 = i19 + 1;
        SVCTX_NTFY_CODE_AUDIO_ONLY_SVC = i20;
        int i21 = i20 + 1;
        SVCTX_NTFY_CODE_VIDEO_ONLY_SVC = i21;
        int i22 = i21 + 1;
        SVCTX_NTFY_CODE_AUDIO_VIDEO_SVC = i22;
        int i23 = i22 + 1;
        SVCTX_NTFY_CODE_SCRAMBLED_AUDIO_VIDEO_SVC = i23;
        int i24 = i23 + 1;
        SVCTX_NTFY_CODE_SCRAMBLED_AUDIO_CLEAR_VIDEO_SVC = i24;
        int i25 = i24 + 1;
        SVCTX_NTFY_CODE_SCRAMBLED_AUDIO_NO_VIDEO_SVC = i25;
        int i26 = i25 + 1;
        SVCTX_NTFY_CODE_SCRAMBLED_VIDEO_CLEAR_AUDIO_SVC = i26;
        int i27 = i26 + 1;
        SVCTX_NTFY_CODE_SCRAMBLED_VIDEO_NO_AUDIO_SVC = i27;
        int i28 = i27 + 1;
        SVCTX_NTFY_CODE_AUDIO_ONLY_STRM = i28;
        int i29 = i28 + 1;
        SVCTX_NTFY_CODE_VIDEO_ONLY_STRM = i29;
        int i30 = i29 + 1;
        SVCTX_NTFY_CODE_WITH_CC_AVIL_INDICATOR = i30;
        int i31 = i30 + 1;
        SVCTX_NTFY_CODE_NO_CC_AVIL_INDICATOR = i31;
        int i32 = i31 + 1;
        SVCTX_NTFY_CODE_EXISTED_CC_IND_CHG = i32;
        int i33 = i32 + 1;
        SVCTX_NTFY_CODE_NO_ANY_STREAM = i33;
        int i34 = i33 + 1;
        SVCTX_NTFY_CODE_NO_STREAM = i34;
        int i35 = i34 + 1;
        SVCTX_NTFY_CODE_STREAM_STOPPED = i35;
        int i36 = i35 + 1;
        SVCTX_NTFY_CODE_STREAM_STARTED = i36;
        int i37 = i36 + 1;
        SVCTX_NTFY_CODE_VIDEO_FMT_UPDATE = i37;
        int i38 = i37 + 1;
        SVCTX_NTFY_CODE_AUDIO_FMT_UPDATE = i38;
        int i39 = i38 + 1;
        SVCTX_NTFY_CODE_VIDEO_AUTO_CLK_POS_PHS_DONE = i39;
        int i40 = i39 + 1;
        SVCTX_NTFY_CODE_VIDEO_AUTO_COLOR_DONE = i40;
        int i41 = i40 + 1;
        SVCTX_NTFY_CODE_VIDEO_ANA_COLOR_SYSTEM = i41;
        int i42 = i41 + 1;
        SVCTX_NTFY_CODE_STREAM_STOPPED_AS_BLOCKED = i42;
        int i43 = i42 + 1;
        SVCTX_NTFY_CODE_STREAM_STARTED_AS_BLOCKED = i43;
        int i44 = i43 + 1;
        SVCTX_NTFY_CODE_VIDEO_FMT_UPDATE_AS_BLOCKED = i44;
        int i45 = i44 + 1;
        SVCTX_NTFY_CODE_AUDIO_DMUTE_AMUTE = i45;
        int i46 = i45 + 1;
        SVCTX_NTFY_CODE_AUDIO_DUNMUTE_AMUTE = i46;
        int i47 = i46 + 1;
        SVCTX_NTFY_CODE_AUDIO_DUNMUTE_AUNMUTE = i47;
        int i48 = i47 + 1;
        SVCTX_NTFY_CODE_AUDIO_DMUTE_AUNMUTE = i48;
        int i49 = i48 + 1;
        SVCTX_NTFY_CODE_UHD_420_SIGNAL_DETECTED = i49;
        int i50 = i49 + 1;
        SVCTX_NTFY_CODE_UHD_420_SIGNAL_NOT_DETECTED = i50;
        int i51 = i50 + 1;
        SVCTX_NTFY_CODE_AUDIO_AUTO_MUTE = i51;
        int i52 = i51 + 1;
        SVCTX_NTFY_CODE_AUDIO_AUTO_UNMUTE = i52;
        int i53 = i52 + 1;
        SVCTX_NTFY_CODE_VIDEO_AUTO_MUTE = i53;
        int i54 = i53 + 1;
        SVCTX_NTFY_CODE_VIDEO_AUTO_UNMUTE = i54;
        int i55 = i54 + 1;
        SVCTX_NTFY_CODE_VIDEO_PLAY_DONE = i55;
        int i56 = i55 + 1;
        SVCTX_NTFY_CODE_SCDB_ADD = i56;
        int i57 = i56 + 1;
        SVCTX_NTFY_CODE_SCDB_DEL = i57;
        int i58 = i57 + 1;
        SVCTX_NTFY_CODE_SCDB_MODIFY = i58;
        int i59 = i58 + 1;
        SVCTX_NTFY_CODE_NO_RESOURCES = i59;
        int i60 = i59 + 1;
        SVCTX_NTFY_CODE_INTERNAL_ERROR = i60;
        int i61 = i60 + 1;
        SVCTX_NTFY_CODE_CA = i61;
        int i62 = i61 + 1;
        SVCTX_NTFY_CODE_CP = i62;
        int i63 = i62 + 1;
        SVCTX_NTFY_CODE_TUNER_SIGNAL_LOCKED = i63;
        int i64 = i63 + 1;
        SVCTX_NTFY_CODE_TUNER_SIGNAL_LOSS = i64;
        int i65 = i64 + 1;
        SVCTX_NTFY_CODE_CH_SRC_FROM_TUNER = i65;
        int i66 = i65 + 1;
        SVCTX_NTFY_CODE_CH_SRC_FROM_SCART = i66;
        int i67 = i66 + 1;
        SVCTX_NTFY_CODE_RF_SCAN_REQUIRED = i67;
        int i68 = i67 + 1;
        SVCTX_NTFY_CODE_UNFREEZE = i68;
        int i69 = i68 + 1;
        SVCTX_NTFY_CODE_TV_SYS_DETECTED = i69;
        int i70 = i69 + 1;
        SVCTX_NTFY_CODE_AUD_SYS_DETECTED = i70;
        int i71 = i70 + 1;
        SVCTX_NTFY_CODE_START_ALTER_FREQ_TUNE = i71;
        int i72 = i71 + 1;
        SVCTX_NTFY_CODE_END_ALTER_FREQ_TUNE = i72;
        int i73 = i72 + 1;
        SVCTX_NTFY_CODE_START_FIRST_TUNE = i73;
        int i74 = i73 + 1;
        SVCTX_NTFY_CODE_END_FIRST_TUNE = i74;
        int i75 = i74 + 1;
        SVCTX_NTFY_CODE_START_FREQ_LIST_UPDATED_CHK = i75;
        int i76 = i75 + 1;
        SVCTX_NTFY_CODE_END_FREQ_LIST_UPDATED_CHK = i76;
        int i77 = i76 + 1;
        SVCTX_NTFY_CODE_MEDIA_LOST = i77;
        int i78 = i77 + 1;
        SVCTX_NTFY_CODE_MEDIA_PRE_PROCESSING = i78;
        int i79 = i78 + 1;
        SVCTX_NTFY_CODE_MEDIA_PRE_PROCESSED = i79;
        int i80 = i79 + 1;
        SVCTX_NTFY_CODE_MEDIA_PB_RANGE_ALLOC = i80;
        int i81 = i80 + 1;
        SVCTX_NTFY_CODE_MEDIA_ERROR = i81;
        int i82 = i81 + 1;
        SVCTX_NTFY_CODE_MEDIA_CAM_CARD_MISSING = i82;
        int i83 = i82 + 1;
        SVCTX_NTFY_CODE_SERVICE_LICENSE_TIMEOUT_BLOCKED = i83;
        int i84 = i83 + 1;
        SVCTX_NTFY_CODE_SERVICE_LICENSE_TIMEOUT_UNBLOCKED = i84;
        int i85 = i84 + 1;
        SVCTX_NTFY_CODE_SERVICE_PIN_BLOCKED = i85;
        int i86 = i85 + 1;
        SVCTX_NTFY_CODE_SERVICE_PIN_UNBLOCKED = i86;
        int i87 = i86 + 1;
        SVCTX_NTFY_CODE_MEDIA_CHAPTER_UPDATE = i87;
        int i88 = i87 + 1;
        SVCTX_NTFY_CODE_MEDIA_TITLE_UPDATE = i88;
        int i89 = i88 + 1;
        SVCTX_NTFY_CODE_MEDIA_DURATION_UPDATE = i89;
        int i90 = i89 + 1;
        SVCTX_NTFY_CODE_MEDIA_SPEED_UPDATE = i90;
        int i91 = i90 + 1;
        SVCTX_NTFY_CODE_MEDIA_AB_REPEAT_DONE = i91;
        int i92 = i91 + 1;
        SVCTX_NTFY_CODE_MEDIA_UOP_INVALID = i92;
        int i93 = i92 + 1;
        SVCTX_NTFY_CODE_MEDIA_SEEK_READY = i93;
        int i94 = i93 + 1;
        SVCTX_NTFY_CODE_MEDIA_SEEK_ERROR = i94;
        int i95 = i94 + 1;
        SVCTX_NTFY_CODE_MEDIA_REPEAT_DONE = i95;
        int i96 = i95 + 1;
        SVCTX_NTFY_CODE_MEDIA_MENU_PRESNT = i96;
        int i97 = i96 + 1;
        SVCTX_NTFY_CODE_MEDIA_EOS = i97;
        int i98 = i97 + 1;
        SVCTX_NTFY_CODE_MEDIA_AS_CODEC_NOT_SUPPORT = i98;
        int i99 = i98 + 1;
        SVCTX_NTFY_CODE_MEDIA_VS_CODEC_NOT_SUPPORT = i99;
        int i100 = i99 + 1;
        SVCTX_NTFY_CODE_MEDIA_AS_BIT_RATE_CHG = i100;
        int i101 = i100 + 1;
        SVCTX_NTFY_CODE_MEDIA_VS_BIT_RATE_CHG = i101;
        int i102 = i101 + 1;
        SVCTX_NTFY_CODE_MEDIA_THUMBNAIL_DONE = i102;
        int i103 = i102 + 1;
        SVCTX_NTFY_CODE_MEDIA_THUMBNAIL_CANCEL = i103;
        int i104 = i103 + 1;
        SVCTX_NTFY_CODE_MEDIA_HD_NOT_SUPPORT = i104;
        int i105 = i104 + 1;
        SVCTX_NTFY_CODE_MEDIA_DRM_NOT_SUPPORT = i105;
        int i106 = i105 + 1;
        SVCTX_NTFY_CODE_MEDIA_SUBTITLE_FMT_UPDATE = i106;
        int i107 = i106 + 1;
        SVCTX_NTFY_CODE_REACH_VALID_RANGE_START = i107;
        int i108 = i107 + 1;
        SVCTX_NTFY_CODE_REACH_VALID_RANGE_END = i108;
        int i109 = i108 + 1;
        SVCTX_NTFY_CODE_OUT_OF_SAFE_RANGE_START = i109;
        int i110 = i109 + 1;
        SVCTX_NTFY_CODE_OUT_OF_SAFE_RANGE_END = i110;
        int i111 = i110 + 1;
        SVCTX_NTFY_CODE_TRICK_REACH_VALID_RANGE_END = i111;
        int i112 = i111 + 1;
        SVCTX_NTFY_CODE_PVR_TRICK_REACH_VALID_RANGE_END = i112;
        int i113 = i112 + 1;
        SVCTX_NTFY_CODE_SEEK_REACH_VALID_RANGE_END = i113;
        int i114 = i113 + 1;
        SVCTX_NTFY_CODE_MEDIA_BAD_TICK_Y_TO_N = i114;
        int i115 = i114 + 1;
        SVCTX_NTFY_CODE_MEDIA_BAD_TICK_N_TO_Y = i115;
        int i116 = i115 + 1;
        SVCTX_NTFY_CODE_MEDIA_FILE_NOT_SUPPORT = i116;
        int i117 = i116 + 1;
        SVCTX_NTFY_CODE_MEDIA_RESOLUTION_NOT_SUPPORT = i117;
        int i118 = i117 + 1;
        SVCTX_NTFY_CODE_MEDIA_FRAMERATE_NOT_SUPPORT = i118;
        int i119 = i118 + 1;
        SVCTX_NTFY_CODE_MEDIA_NO_CONTENT = i119;
        int i120 = i119 + 1;
        SVCTX_NTFY_CODE_MEDIA_RANGE_AB_DONE = i120;
        int i121 = i120 + 1;
        SVCTX_NTFY_CODE_MEDIA_VIDEO_PRESENT = i121;
        int i122 = i121 + 1;
        SVCTX_NTFY_CODE_MEDIA_VS_BIT_RATE = i122;
        int i123 = i122 + 1;
        SVCTX_NTFY_CODE_MEDIA_REPLAY = i123;
        int i124 = i123 + 1;
        SVCTX_NTFY_CODE_MEDIA_URI_FILE_OPENED = i124;
        int i125 = i124 + 1;
        SVCTX_NTFY_CODE_MEDIA_DESC_ALLOCED = i125;
        int i126 = i125 + 1;
        SVCTX_NTFY_CODE_MEDIA_RATING_BLOCKED = i126;
        int i127 = i126 + 1;
        SVCTX_NTFY_CODE_MEDIA_RATING_UNBLOCKED = i127;
        int i128 = i127 + 1;
        SVCTX_NTFY_CODE_MEDIA_PVR_THUMBNAIL_PARENT_RATING = i128;
        int i129 = i128 + 1;
        SVCTX_NTFY_CODE_MEDIA_PVR_PLAYING_PARENT_RATING = i129;
        int i130 = i129 + 1;
        SVCTX_NTFY_CODE_MEDIA_PVR_PROG_BLOCKED = i130;
        int i131 = i130 + 1;
        SVCTX_NTFY_CODE_MEDIA_GUIDANCE_BLOCKED_DUR_THUMB = i131;
        int i132 = i131 + 1;
        SVCTX_NTFY_CODE_MEDIA_GUIDANCE_BLOCKED_AFT_THUMB = i132;
        int i133 = i132 + 1;
        SVCTX_NTFY_CODE_MEDIA_PAUSE_STATUS = i133;
        int i134 = i133 + 1;
        SVCTX_NTFY_CODE_INP_SIGNAL_UNKNOWN = i134;
        int i135 = i134 + 1;
        SVCTX_NTFY_CODE_HDCP_DETECT = i135;
        int i136 = i135 + 1;
        SVCTX_NTFY_CODE_HDCP_NOT_DETECT = i136;
        int i137 = i136 + 1;
        SVCTX_NTFY_CODE_MACROVISION_DETECT = i137;
        int i138 = i137 + 1;
        SVCTX_NTFY_CODE_MACROVISION_NOT_DETECT = i138;
        int i139 = i138 + 1;
        SVCTX_NTFY_CODE_EWS_ON = i139;
        int i140 = i139 + 1;
        SVCTX_NTFY_CODE_EWS_OFF = i140;
        int i141 = i140 + 1;
        SVCTX_NTFY_CODE_BRDCSTING_SVC = i141;
        int i142 = i141 + 1;
        SVCTX_NTFY_CODE_NON_BRDCSTING_SVC = i142;
        int i143 = i142 + 1;
        SVCTX_NTFY_CODE_DVBS_SHORT_ON = i143;
        int i144 = i143 + 1;
        SVCTX_NTFY_CODE_DVBS_SHORT_OFF = i144;
        int i145 = i144 + 1;
        SVCTX_NTFY_CODE_REC_STARTED = i145;
        int i146 = i145 + 1;
        SVCTX_NTFY_CODE_REC_STOPPED = i146;
        int i147 = i146 + 1;
        SVCTX_NTFY_CODE_REC_PAUSED = i147;
        int i148 = i147 + 1;
        SVCTX_NTFY_CODE_REC_SOURCE_READY = i148;
        int i149 = i148 + 1;
        SVCTX_NTFY_CODE_REC_REQ_ES_LIST = i149;
        int i150 = i149 + 1;
        SVCTX_NTFY_CODE_REC_REQ_STOP = i150;
        int i151 = i150 + 1;
        SVCTX_NTFY_CODE_PIN_CAP_CHANGE = i151;
        int i152 = i151 + 1;
        SVCTX_NTFY_CODE_REC_ES_AUTH_UPDATED = i152;
        int i153 = i152 + 1;
        SVCTX_NTFY_CODE_REC_REACH_BOUND = i153;
        int i154 = i153 + 1;
        SVCTX_NTFY_CODE_REC_REACH_TIME_BOUND = i154;
        int i155 = i154 + 1;
        SVCTX_NTFY_CODE_REC_BUF_FULL = i155;
        int i156 = i155 + 1;
        SVCTX_NTFY_CODE_REC_UNAUTHORIZED = i156;
        int i157 = i156 + 1;
        SVCTX_NTFY_CODE_REC_BLOCKED = i157;
        int i158 = i157 + 1;
        SVCTX_NTFY_CODE_REC_STRG_FULL = i158;
        int i159 = i158 + 1;
        SVCTX_NTFY_CODE_REC_BITRATE_TOO_HIGH = i159;
        int i160 = i159 + 1;
        SVCTX_NTFY_CODE_REC_NOT_SUPPORTED = i160;
        int i161 = i160 + 1;
        SVCTX_NTFY_CODE_REC_STRG_ERROR = i161;
        int i162 = i161 + 1;
        SVCTX_NTFY_CODE_REC_INTERNAL_ERROR = i162;
        int i163 = i162 + 1;
        SVCTX_NTFY_CODE_REC_BAD_TICK = i163;
        int i164 = i163 + 1;
        SVCTX_NTFY_CODE_REC_CHANNEL_LOCKED = i164;
        int i165 = i164 + 1;
        SVCTX_NTFY_CODE_REC_PIN_ERROR = i165;
        int i166 = i165 + 1;
        SVCTX_NTFY_CODE_REC_18_PLUS_LOCKED = i166;
        int i167 = i166 + 1;
        SVCTX_NTFY_CODE_CHAPTER_CHANGE = i167;
        int i168 = i167 + 1;
        SVCTX_NTFY_CODE_CONNECTION_ANA_FREQ = i168;
        int i169 = i168 + 1;
        SVCTX_NTFY_CODE_ANA_AUTO_DETECTED_AUD_SYS = i169;
        int i170 = i169 + 1;
        SVCTX_NTFY_CODE_BUF_READY = i170;
        int i171 = i170 + 1;
        SVCTX_NTFY_CODE_MEDIA_TIME_UPDATE = i171;
        int i172 = i171 + 1;
        SVCTX_NTFY_CODE_MEDIA_UNDERFLOW = i172;
        int i173 = i172 + 1;
        SVCTX_NTFY_CODE_MEDIA_EOF = i173;
        int i174 = i173 + 1;
        SVCTX_NTFY_CODE_MEDIA_CLEAR_EOF = i174;
        int i175 = i174 + 1;
        SVCTX_NTFY_CODE_MEDIA_AUDIO_SWITCH_DONE = i175;
        int i176 = i175 + 1;
        SVCTX_NTFY_CODE_MEDIA_GET_IFRAME = i176;
        int i177 = i176 + 1;
        SVCTX_NTFY_CODE_STREAM_OPENED = i177;
        int i178 = i177 + 1;
        SVCTX_NTFY_CODE_VIDEO_NUM_READY = i178;
        int i179 = i178 + 1;
        SVCTX_NTFY_CODE_MEDIA_MSGQ_FULL = i179;
        int i180 = i179 + 1;
        SVCTX_NTFY_CODE_MEDIA_MSGQ_EMPTY = i180;
        int i181 = i180 + 1;
        SVCTX_NTFY_CODE_DRM_STATUS_START = i181;
        int i182 = i181 + 1;
        SVCTX_NTFY_CODE_DRM_UNKNOWN_ERR = i182;
        int i183 = i182 + 1;
        SVCTX_NTFY_CODE_DRM_LIC_EXPIRATION_ERR = i183;
        int i184 = i183 + 1;
        SVCTX_NTFY_CODE_DRM_SRVDATA_ACCESS_FAIL = i184;
        int i185 = i184 + 1;
        SVCTX_NTFY_CODE_DRM_INV_BUSINESS_TKN = i185;
        int i186 = i185 + 1;
        SVCTX_NTFY_CODE_DRM_CERT_EXPIRED = i186;
        int i187 = i186 + 1;
        SVCTX_NTFY_CODE_DRM_LIC_NOT_ALLOW = i187;
        int i188 = i187 + 1;
        SVCTX_NTFY_CODE_DRM_SRV_END = i188;
        int i189 = i188 + 1;
        SVCTX_NTFY_CODE_DRM_SRV_UNAVAIL = i189;
        int i190 = i189 + 1;
        SVCTX_NTFY_CODE_DRM_SRV_BUSY = i190;
        int i191 = i190 + 1;
        SVCTX_NTFY_CODE_DRM_DEV_NOT_REG = i191;
        int i192 = i191 + 1;
        SVCTX_NTFY_CODE_DRM_CONTENT_EXHAUSTED = i192;
        int i193 = i192 + 1;
        SVCTX_NTFY_CODE_DRM_UNKNOWN_SRV_ERR = i193;
        int i194 = i193 + 1;
        SVCTX_NTFY_CODE_DRM_INV_USR_AGENT = i194;
        int i195 = i194 + 1;
        SVCTX_NTFY_CODE_DRM_UNSUPPORTED_VER = i195;
        int i196 = i195 + 1;
        SVCTX_NTFY_CODE_DRM_INV_CONTENT_TYPE = i196;
        int i197 = i196 + 1;
        SVCTX_NTFY_CODE_DRM_INV_SRV_TKN = i197;
        int i198 = i197 + 1;
        SVCTX_NTFY_CODE_DRM_INV_ASSET_ID = i198;
        int i199 = i198 + 1;
        SVCTX_NTFY_CODE_DRM_INIT_ERROR = i199;
        int i200 = i199 + 1;
        SVCTX_NTFY_CODE_DRM_LICENSE_EXPIRED_ERROR = i200;
        int i201 = i200 + 1;
        SVCTX_NTFY_CODE_DRM_LICENSE_ACQUISITION_ERROR = i201;
        int i202 = i201 + 1;
        SVCTX_NTFY_CODE_DRM_LICENSE_SERVER_CONNECTION_ERROR = i202;
        int i203 = i202 + 1;
        SVCTX_NTFY_CODE_DRM_TOKEN_ACQUISITION_ERROR = i203;
        int i204 = i203 + 1;
        SVCTX_NTFY_CODE_DRM_CAD_ACQUISITION_ERROR = i204;
        int i205 = i204 + 1;
        SVCTX_NTFY_CODE_CMPB_QUERY = i205;
        int i206 = i205 + 1;
        SVCTX_NTFY_CODE_CC_IDX_CHANGED = i206;
        int i207 = i206 + 1;
        SVCTX_NTFY_CODE_CC_ATTR_CHANGED = i207;
        int i208 = i207 + 1;
        SVCTX_NTFY_CODE_VIDEO_STREAM_CTR_NOT_SUPPORT = i208;
        int i209 = i208 + 1;
        SVCTX_NTFY_CODE_AUDIO_STREAM_CTR_NOT_SUPPORT = i209;
        int i210 = i209 + 1;
        SVCTX_NTFY_CODE_VIDEO_WFD_ERROR = i210;
        int i211 = i210 + 1;
        SVCTX_NTFY_CODE_CONN_PMT_UPDATED = i211;
        int i212 = i211 + 1;
        SVCTX_NTFY_CODE_CAM_CARD_REMOVE = i212;
        int i213 = i212 + 1;
        SVCTX_NTFY_CODE_MEDIA_FILE_OPER_ERROR = i213;
        int i214 = i213 + 1;
        SVCTX_NTFY_CODE_REC_INPUT_LOCKED = i214;
        int i215 = i214 + 1;
        SVCTX_NTFY_CODE_PSI_TABLE_UPDATE = i215;
        int i216 = i215 + 1;
        SVCTX_NTFY_CODE_DRM_INVALID_ARG = i216;
        int i217 = i216 + 1;
        SVCTX_NTFY_CODE_DRM_UNKNOW_DRMTYPE = i217;
        int i218 = i217 + 1;
        SVCTX_NTFY_CODE_DRM_LICENSE_INVALID = i218;
        int i219 = i218 + 1;
        SVCTX_NTFY_CODE_DRM_GET_KEY_ERROR = i219;
        int i220 = i219 + 1;
        SVCTX_NTFY_CODE_DRM_CAD_INVALID = i220;
        int i221 = i220 + 1;
        SVCTX_NTFY_CODE_DRM_NO_MARLIN_KEY = i221;
        int i222 = i221 + 1;
        SVCTX_NTFY_CODE_DRM_NOT_MARLIN_MS3_URL = i222;
        int i223 = i222 + 1;
        SVCTX_NTFY_CODE_DRM_MARLIN_KEY_FORMATERROR = i223;
        int i224 = i223 + 1;
        SVCTX_NTFY_CODE_DRM_TYPE_MARLIN = i224;
        int i225 = i224 + 1;
        SVCTX_NTFY_CODE_DRM_TYPE_NAUTILUS_MARLIN = i225;
        SVCTX_NTFY_CODE_DRM_TYPE_PLAYREADY = i225 + 1;
    }
}
